package com.vircarmen.botica.entity;

public enum FormaFarmaceutica {
    TABLETA, CAPSULA, COMPRIMIDO, SUSPENSION_ORAL, JARABE, SOLUCION_ORAL, GOTAS, CREMA, POMADA, GEL, UNGUENTO, LOCION, SPRAY, INYECCION, SUPOSITORIO, OVULO, POLVO, AEROSOL, OTRO
}
