--
-- PostgreSQL database dump
--

\restrict 2uQwSnjd2dyN4DwmBFf1ddpnAeIFwWc4o5ZymFvnzTaV7NlrUQ3dHfyAsr51JkS

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-08-24 23:09:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 17297)
-- Name: caja_sesiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caja_sesiones (
    id_caja_sesion integer NOT NULL,
    creado_por character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    modificado_por character varying(255),
    estado character varying(20),
    fecha_apertura timestamp(6) without time zone NOT NULL,
    fecha_cierre timestamp(6) without time zone,
    monto_final numeric(10,2),
    monto_inicial numeric(10,2) NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT caja_sesiones_estado_check CHECK (((estado)::text = ANY ((ARRAY['ABIERTA'::character varying, 'CERRADA'::character varying])::text[])))
);


ALTER TABLE public.caja_sesiones OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17296)
-- Name: caja_sesiones_id_caja_sesion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caja_sesiones ALTER COLUMN id_caja_sesion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_sesiones_id_caja_sesion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17310)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    descripcion text,
    estado character(1),
    nombre character varying(100) NOT NULL,
    CONSTRAINT categorias_estado_check CHECK ((estado = ANY (ARRAY['A'::bpchar, 'I'::bpchar])))
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17309)
-- Name: categorias_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17321)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    id_cliente integer NOT NULL,
    direccion character varying(255),
    nombre_razon_social character varying(200) NOT NULL,
    numero_documento character varying(15) NOT NULL,
    tipo_documento character varying(20) NOT NULL
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17320)
-- Name: clientes_id_cliente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17331)
-- Name: compras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compras (
    id_compra integer NOT NULL,
    documento character varying(50) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_compra timestamp(6) without time zone NOT NULL,
    total numeric(10,2) NOT NULL,
    proveedor_id integer NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT compras_estado_check CHECK (((estado)::text = ANY ((ARRAY['REGISTRADA'::character varying, 'ANULADA'::character varying])::text[])))
);


ALTER TABLE public.compras OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17330)
-- Name: compras_id_compra_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.compras ALTER COLUMN id_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_id_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17345)
-- Name: comprobantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comprobantes (
    id_comprobante integer NOT NULL,
    correlativo character varying(20) NOT NULL,
    fecha_emision timestamp(6) without time zone NOT NULL,
    igv numeric(10,2) NOT NULL,
    serie character varying(10) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tipo_comprobante character varying(20) NOT NULL,
    total numeric(10,2) NOT NULL,
    cliente_id integer,
    venta_id integer NOT NULL,
    CONSTRAINT comprobantes_tipo_comprobante_check CHECK (((tipo_comprobante)::text = ANY ((ARRAY['BOLETA'::character varying, 'FACTURA'::character varying, 'TICKET'::character varying])::text[])))
);


ALTER TABLE public.comprobantes OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17344)
-- Name: comprobantes_id_comprobante_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comprobantes ALTER COLUMN id_comprobante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comprobantes_id_comprobante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17361)
-- Name: detalle_compras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_compras (
    id_detalle_compra integer NOT NULL,
    cantidad integer NOT NULL,
    costo_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    compra_id integer NOT NULL,
    lote_id integer NOT NULL,
    producto_id integer NOT NULL
);


ALTER TABLE public.detalle_compras OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17360)
-- Name: detalle_compras_id_detalle_compra_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_compras ALTER COLUMN id_detalle_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_compras_id_detalle_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17374)
-- Name: detalle_movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_movimientos (
    id_detalle integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    lote_id integer NOT NULL,
    movimiento_id integer NOT NULL
);


ALTER TABLE public.detalle_movimientos OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17373)
-- Name: detalle_movimientos_id_detalle_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_movimientos ALTER COLUMN id_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_movimientos_id_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17385)
-- Name: detalle_ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_ventas (
    id_detalle_venta integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    lote_id integer NOT NULL,
    venta_id integer NOT NULL
);


ALTER TABLE public.detalle_ventas OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17384)
-- Name: detalle_ventas_id_detalle_venta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_ventas ALTER COLUMN id_detalle_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_ventas_id_detalle_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17397)
-- Name: laboratorios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laboratorios (
    id_laboratorio integer NOT NULL,
    creado_por character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    modificado_por character varying(255),
    descripcion character varying(200),
    estado character(1),
    nombre character varying(150) NOT NULL,
    CONSTRAINT laboratorios_estado_check CHECK ((estado = ANY (ARRAY['A'::bpchar, 'I'::bpchar])))
);


ALTER TABLE public.laboratorios OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17396)
-- Name: laboratorios_id_laboratorio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laboratorios ALTER COLUMN id_laboratorio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratorios_id_laboratorio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 17408)
-- Name: lotes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lotes (
    id_lote integer NOT NULL,
    codigo_lote character varying(50) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_ingreso date NOT NULL,
    fecha_vencimiento date NOT NULL,
    precio_compra numeric(10,2),
    stock_actual integer NOT NULL,
    stock_inicial integer NOT NULL,
    producto_id integer NOT NULL,
    CONSTRAINT lotes_estado_check CHECK (((estado)::text = ANY ((ARRAY['DISPONIBLE'::character varying, 'AGOTADO'::character varying, 'VENCIDO'::character varying, 'BLOQUEADO'::character varying, 'RETIRADO'::character varying])::text[])))
);


ALTER TABLE public.lotes OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17407)
-- Name: lotes_id_lote_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lotes ALTER COLUMN id_lote ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lotes_id_lote_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17423)
-- Name: movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos (
    id_movimiento integer NOT NULL,
    fecha_movimiento timestamp(6) without time zone NOT NULL,
    motivo character varying(300),
    referencia_anulacion integer,
    tipo_movimiento character varying(255) NOT NULL,
    proveedor_id integer,
    usuario_id integer NOT NULL,
    CONSTRAINT movimientos_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['INGRESO'::character varying, 'SALIDA'::character varying, 'AJUSTE'::character varying, 'ANULACION'::character varying])::text[])))
);


ALTER TABLE public.movimientos OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17436)
-- Name: movimientos_caja; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos_caja (
    id_movimiento_caja integer NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    monto numeric(10,2) NOT NULL,
    motivo character varying(255) NOT NULL,
    tipo_movimiento character varying(20) NOT NULL,
    caja_sesion_id integer NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT movimientos_caja_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['INGRESO'::character varying, 'EGRESO'::character varying])::text[])))
);


ALTER TABLE public.movimientos_caja OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17435)
-- Name: movimientos_caja_id_movimiento_caja_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos_caja ALTER COLUMN id_movimiento_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_caja_id_movimiento_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17422)
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 17450)
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id_pago integer NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_pago timestamp(6) without time zone NOT NULL,
    metodo_pago character varying(20) NOT NULL,
    monto numeric(10,2) NOT NULL,
    referencia character varying(100),
    caja_sesion_id integer NOT NULL,
    venta_id integer NOT NULL,
    CONSTRAINT pagos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'APROBADO'::character varying, 'RECHAZADO'::character varying, 'ANULADO'::character varying])::text[]))),
    CONSTRAINT pagos_metodo_pago_check CHECK (((metodo_pago)::text = ANY ((ARRAY['EFECTIVO'::character varying, 'YAPE'::character varying, 'PLIN'::character varying, 'TARJETA'::character varying])::text[])))
);


ALTER TABLE public.pagos OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17449)
-- Name: pagos_id_pago_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_pago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17465)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id_producto integer NOT NULL,
    creado_por character varying(255),
    fecha_creacion timestamp(6) without time zone,
    fecha_modificacion timestamp(6) without time zone,
    modificado_por character varying(255),
    codigo_barras character varying(50),
    codigo_sunat character varying(20),
    estado character(1),
    forma_farmaceutica character varying(30),
    nombre character varying(200) NOT NULL,
    precio_presentacion numeric(10,2),
    precio_venta numeric(10,2),
    presentacion character varying(100),
    principio_activo character varying(200),
    requiere_receta boolean,
    stock_actual integer,
    stock_minimo integer,
    tipo_afectacion_igv character varying(2),
    unidad_medida character varying(20),
    unidades_por_presentacion integer,
    categoria_id integer NOT NULL,
    laboratorio_id integer,
    CONSTRAINT productos_estado_check CHECK ((estado = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))),
    CONSTRAINT productos_forma_farmaceutica_check CHECK (((forma_farmaceutica)::text = ANY ((ARRAY['TABLETA'::character varying, 'CAPSULA'::character varying, 'COMPRIMIDO'::character varying, 'SUSPENSION_ORAL'::character varying, 'JARABE'::character varying, 'SOLUCION_ORAL'::character varying, 'GOTAS'::character varying, 'CREMA'::character varying, 'POMADA'::character varying, 'GEL'::character varying, 'UNGUENTO'::character varying, 'LOCION'::character varying, 'SPRAY'::character varying, 'INYECCION'::character varying, 'SUPOSITORIO'::character varying, 'OVULO'::character varying, 'POLVO'::character varying, 'AEROSOL'::character varying, 'OTRO'::character varying])::text[]))),
    CONSTRAINT productos_unidad_medida_check CHECK (((unidad_medida)::text = ANY ((ARRAY['UNIDAD'::character varying, 'BLISTER'::character varying, 'CAJA'::character varying, 'FRASCO'::character varying, 'MILILITRO'::character varying, 'LITRO'::character varying, 'GRAMO'::character varying, 'KILOGRAMO'::character varying, 'AMPOLLA'::character varying, 'SOBRE'::character varying])::text[])))
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17464)
-- Name: productos_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 17479)
-- Name: proveedores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedores (
    id_proveedor integer NOT NULL,
    correo character varying(150),
    direccion character varying(250),
    estado character(1),
    razon_social character varying(200) NOT NULL,
    ruc character varying(11) NOT NULL,
    telefono character varying(20),
    CONSTRAINT proveedores_estado_check CHECK ((estado = ANY (ARRAY['A'::bpchar, 'I'::bpchar])))
);


ALTER TABLE public.proveedores OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17478)
-- Name: proveedores_id_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proveedores ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedores_id_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 17491)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    estado character(1),
    fecha_creacion timestamp(6) without time zone,
    nombre_completo character varying(200) NOT NULL,
    password_hash character varying(255) NOT NULL,
    rol character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT usuarios_estado_check CHECK ((estado = ANY (ARRAY['A'::bpchar, 'I'::bpchar]))),
    CONSTRAINT usuarios_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'CAJERO'::character varying, 'ALMACENERO'::character varying])::text[])))
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17490)
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 17506)
-- Name: ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ventas (
    id_venta integer NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_emision timestamp(6) without time zone NOT NULL,
    igv numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    caja_sesion_id integer NOT NULL,
    cliente_id integer,
    usuario_id integer NOT NULL,
    CONSTRAINT ventas_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADA'::character varying, 'ANULADA'::character varying])::text[])))
);


ALTER TABLE public.ventas OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 17505)
-- Name: ventas_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ventas ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5179 (class 0 OID 17297)
-- Dependencies: 220
-- Data for Name: caja_sesiones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caja_sesiones (id_caja_sesion, creado_por, fecha_creacion, fecha_modificacion, modificado_por, estado, fecha_apertura, fecha_cierre, monto_final, monto_inicial, usuario_id) FROM stdin;
1	\N	2026-08-19 16:11:05.097889	2026-08-19 16:11:05.097889	\N	ABIERTA	2026-08-19 16:11:05.0644	\N	\N	10000.00	1
2	\N	2026-08-24 19:00:27.950077	2026-08-24 19:00:33.846094	\N	CERRADA	2026-08-24 19:00:27.942484	2026-08-24 19:00:33.840134	10000.00	0.00	2
3	\N	2026-08-24 19:00:36.046889	2026-08-24 19:00:45.288813	\N	CERRADA	2026-08-24 19:00:36.046889	2026-08-24 19:00:45.284801	1000.00	0.00	2
4	\N	2026-08-24 19:00:46.789382	2026-08-24 19:00:46.789382	\N	ABIERTA	2026-08-24 19:00:46.788375	\N	\N	0.00	2
\.


--
-- TOC entry 5181 (class 0 OID 17310)
-- Dependencies: 222
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorias (id_categoria, descripcion, estado, nombre) FROM stdin;
1	\N	A	Analgsicos
2	\N	A	Antibticos
3	\N	A	Vitaminas
\.


--
-- TOC entry 5183 (class 0 OID 17321)
-- Dependencies: 224
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (id_cliente, direccion, nombre_razon_social, numero_documento, tipo_documento) FROM stdin;
1	-	Cliente Pblico General	00000000	DNI
\.


--
-- TOC entry 5185 (class 0 OID 17331)
-- Dependencies: 226
-- Data for Name: compras; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compras (id_compra, documento, estado, fecha_compra, total, proveedor_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5187 (class 0 OID 17345)
-- Dependencies: 228
-- Data for Name: comprobantes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comprobantes (id_comprobante, correlativo, fecha_emision, igv, serie, subtotal, tipo_comprobante, total, cliente_id, venta_id) FROM stdin;
1	00000001	2026-08-19 16:11:31.836447	0.38	B001	2.12	BOLETA	2.50	1	1
2	00000002	2026-08-19 16:16:24.673075	0.38	B001	2.12	BOLETA	2.50	1	2
3	00000003	2026-08-24 18:56:34.458361	0.38	B001	2.12	BOLETA	2.50	1	3
\.


--
-- TOC entry 5189 (class 0 OID 17361)
-- Dependencies: 230
-- Data for Name: detalle_compras; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_compras (id_detalle_compra, cantidad, costo_unitario, subtotal, compra_id, lote_id, producto_id) FROM stdin;
\.


--
-- TOC entry 5191 (class 0 OID 17374)
-- Dependencies: 232
-- Data for Name: detalle_movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_movimientos (id_detalle, cantidad, precio_unitario, lote_id, movimiento_id) FROM stdin;
\.


--
-- TOC entry 5193 (class 0 OID 17385)
-- Dependencies: 234
-- Data for Name: detalle_ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_ventas (id_detalle_venta, cantidad, precio_unitario, subtotal, lote_id, venta_id) FROM stdin;
1	1	2.50	2.50	1	1
2	1	2.50	2.50	1	2
3	1	2.50	2.50	1	3
\.


--
-- TOC entry 5195 (class 0 OID 17397)
-- Dependencies: 236
-- Data for Name: laboratorios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.laboratorios (id_laboratorio, creado_por, fecha_creacion, fecha_modificacion, modificado_por, descripcion, estado, nombre) FROM stdin;
1	\N	2026-08-19 15:16:03.918399	2026-08-19 15:16:03.918399	\N	Bayer Mxico	A	Bayer
2	\N	2026-08-19 15:16:03.92743	2026-08-19 15:16:03.92743	\N	Pfizer Lab	A	Pfizer
3	\N	2026-08-19 15:16:03.930224	2026-08-19 15:16:03.930224	\N	Genricos	A	Genfar
\.


--
-- TOC entry 5197 (class 0 OID 17408)
-- Dependencies: 238
-- Data for Name: lotes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lotes (id_lote, codigo_lote, estado, fecha_ingreso, fecha_vencimiento, precio_compra, stock_actual, stock_inicial, producto_id) FROM stdin;
2	LT-PARA-002	DISPONIBLE	2026-08-14	2028-08-19	1.55	50	50	1
3	LT-ASP-001	DISPONIBLE	2026-08-17	2028-02-19	0.70	50	50	2
1	LT-PARA-001	DISPONIBLE	2026-08-09	2027-08-19	1.50	97	100	1
\.


--
-- TOC entry 5199 (class 0 OID 17423)
-- Dependencies: 240
-- Data for Name: movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimientos (id_movimiento, fecha_movimiento, motivo, referencia_anulacion, tipo_movimiento, proveedor_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5201 (class 0 OID 17436)
-- Dependencies: 242
-- Data for Name: movimientos_caja; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimientos_caja (id_movimiento_caja, fecha, monto, motivo, tipo_movimiento, caja_sesion_id, usuario_id) FROM stdin;
\.


--
-- TOC entry 5203 (class 0 OID 17450)
-- Dependencies: 244
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagos (id_pago, estado, fecha_pago, metodo_pago, monto, referencia, caja_sesion_id, venta_id) FROM stdin;
1	APROBADO	2026-08-19 16:11:31.775086	EFECTIVO	2.50	\N	1	1
2	APROBADO	2026-08-19 16:16:24.655789	EFECTIVO	2.50	\N	1	2
3	APROBADO	2026-08-24 18:56:34.332932	EFECTIVO	2.50	\N	1	3
\.


--
-- TOC entry 5205 (class 0 OID 17465)
-- Dependencies: 246
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productos (id_producto, creado_por, fecha_creacion, fecha_modificacion, modificado_por, codigo_barras, codigo_sunat, estado, forma_farmaceutica, nombre, precio_presentacion, precio_venta, presentacion, principio_activo, requiere_receta, stock_actual, stock_minimo, tipo_afectacion_igv, unidad_medida, unidades_por_presentacion, categoria_id, laboratorio_id) FROM stdin;
2	\N	2026-08-19 15:16:03.973699	2026-08-19 15:16:03.973699	\N	7759876543210	\N	A	TABLETA	Aspirina 100mg	\N	1.20	\N	cido Acetilsaliclico	f	50	10	10	BLISTER	1	1	1
1	\N	2026-08-19 15:16:03.951264	2026-08-24 18:56:34.464791	\N	7751234567890	\N	A	TABLETA	Paracetamol 500mg	\N	2.50	\N	Paracetamol	f	147	20	10	CAJA	1	1	3
\.


--
-- TOC entry 5207 (class 0 OID 17479)
-- Dependencies: 248
-- Data for Name: proveedores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proveedores (id_proveedor, correo, direccion, estado, razon_social, ruc, telefono) FROM stdin;
1	ventas@droguerialosandes.pe	Av. Universitaria 1234, Lima	A	Droguería Los Andes S.A.C.	20123456789	01 456 7890
\.


--
-- TOC entry 5209 (class 0 OID 17491)
-- Dependencies: 250
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id_usuario, estado, fecha_creacion, nombre_completo, password_hash, rol, username) FROM stdin;
1	A	2026-08-19 15:16:03.662693	Administrador del Sistema	$2a$10$OvwaQNAStRtpOqQjqfsWrueFexHMcDHuTqFb1tm68ggd3axrcfwlu	ADMIN	admin
2	A	2026-08-19 15:16:03.798769	Cajero Principal	$2a$10$rsrrLrZEAQF/lp0ts6LiWujrxP/TfGDDrFlQWQ4upGzB50mL5vq/K	CAJERO	cajero
3	A	2026-08-24 19:46:49.789465	Alendo	$2a$10$wCd2ir.SQxPuAworDxViVuV/frRiuJDVMKeo8QI8SKH7NjOKZeYla	ALMACENERO	almacenero
\.


--
-- TOC entry 5211 (class 0 OID 17506)
-- Dependencies: 252
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ventas (id_venta, estado, fecha_emision, igv, subtotal, total, caja_sesion_id, cliente_id, usuario_id) FROM stdin;
1	PAGADA	2026-08-19 16:11:31.705337	0.38	2.12	2.50	1	1	1
2	PAGADA	2026-08-19 16:16:24.631973	0.38	2.12	2.50	1	1	1
3	PAGADA	2026-08-24 18:56:34.134528	0.38	2.12	2.50	1	1	1
\.


--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 219
-- Name: caja_sesiones_id_caja_sesion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caja_sesiones_id_caja_sesion_seq', 4, true);


--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 221
-- Name: categorias_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_id_categoria_seq', 3, true);


--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 223
-- Name: clientes_id_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_id_cliente_seq', 1, true);


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 225
-- Name: compras_id_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compras_id_compra_seq', 1, false);


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 227
-- Name: comprobantes_id_comprobante_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comprobantes_id_comprobante_seq', 3, true);


--
-- TOC entry 5223 (class 0 OID 0)
-- Dependencies: 229
-- Name: detalle_compras_id_detalle_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_compras_id_detalle_compra_seq', 1, false);


--
-- TOC entry 5224 (class 0 OID 0)
-- Dependencies: 231
-- Name: detalle_movimientos_id_detalle_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_movimientos_id_detalle_seq', 1, false);


--
-- TOC entry 5225 (class 0 OID 0)
-- Dependencies: 233
-- Name: detalle_ventas_id_detalle_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_ventas_id_detalle_venta_seq', 3, true);


--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 235
-- Name: laboratorios_id_laboratorio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.laboratorios_id_laboratorio_seq', 3, true);


--
-- TOC entry 5227 (class 0 OID 0)
-- Dependencies: 237
-- Name: lotes_id_lote_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lotes_id_lote_seq', 3, true);


--
-- TOC entry 5228 (class 0 OID 0)
-- Dependencies: 241
-- Name: movimientos_caja_id_movimiento_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_caja_id_movimiento_caja_seq', 1, false);


--
-- TOC entry 5229 (class 0 OID 0)
-- Dependencies: 239
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimientos_id_movimiento_seq', 1, false);


--
-- TOC entry 5230 (class 0 OID 0)
-- Dependencies: 243
-- Name: pagos_id_pago_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_id_pago_seq', 3, true);


--
-- TOC entry 5231 (class 0 OID 0)
-- Dependencies: 245
-- Name: productos_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_producto_seq', 2, true);


--
-- TOC entry 5232 (class 0 OID 0)
-- Dependencies: 247
-- Name: proveedores_id_proveedor_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proveedores_id_proveedor_seq', 1, true);


--
-- TOC entry 5233 (class 0 OID 0)
-- Dependencies: 249
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_usuario_seq', 3, true);


--
-- TOC entry 5234 (class 0 OID 0)
-- Dependencies: 251
-- Name: ventas_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ventas_id_venta_seq', 3, true);


--
-- TOC entry 4954 (class 2606 OID 17308)
-- Name: caja_sesiones caja_sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_sesiones
    ADD CONSTRAINT caja_sesiones_pkey PRIMARY KEY (id_caja_sesion);


--
-- TOC entry 4956 (class 2606 OID 17319)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria);


--
-- TOC entry 4960 (class 2606 OID 17329)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente);


--
-- TOC entry 4964 (class 2606 OID 17343)
-- Name: compras compras_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT compras_pkey PRIMARY KEY (id_compra);


--
-- TOC entry 4966 (class 2606 OID 17359)
-- Name: comprobantes comprobantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT comprobantes_pkey PRIMARY KEY (id_comprobante);


--
-- TOC entry 4972 (class 2606 OID 17372)
-- Name: detalle_compras detalle_compras_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_compras
    ADD CONSTRAINT detalle_compras_pkey PRIMARY KEY (id_detalle_compra);


--
-- TOC entry 4974 (class 2606 OID 17383)
-- Name: detalle_movimientos detalle_movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_movimientos
    ADD CONSTRAINT detalle_movimientos_pkey PRIMARY KEY (id_detalle);


--
-- TOC entry 4976 (class 2606 OID 17395)
-- Name: detalle_ventas detalle_ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT detalle_ventas_pkey PRIMARY KEY (id_detalle_venta);


--
-- TOC entry 4978 (class 2606 OID 17406)
-- Name: laboratorios laboratorios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios
    ADD CONSTRAINT laboratorios_pkey PRIMARY KEY (id_laboratorio);


--
-- TOC entry 4982 (class 2606 OID 17421)
-- Name: lotes lotes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT lotes_pkey PRIMARY KEY (id_lote);


--
-- TOC entry 4986 (class 2606 OID 17448)
-- Name: movimientos_caja movimientos_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT movimientos_caja_pkey PRIMARY KEY (id_movimiento_caja);


--
-- TOC entry 4984 (class 2606 OID 17434)
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id_movimiento);


--
-- TOC entry 4988 (class 2606 OID 17463)
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id_pago);


--
-- TOC entry 4990 (class 2606 OID 17477)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id_producto);


--
-- TOC entry 4996 (class 2606 OID 17489)
-- Name: proveedores proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id_proveedor);


--
-- TOC entry 4962 (class 2606 OID 17523)
-- Name: clientes uk2viccgf178bd74vfbq8ctsv8t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk2viccgf178bd74vfbq8ctsv8t UNIQUE (numero_documento);


--
-- TOC entry 4980 (class 2606 OID 17529)
-- Name: laboratorios uka9xwubi6lhgs5if65yiu1q6fj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laboratorios
    ADD CONSTRAINT uka9xwubi6lhgs5if65yiu1q6fj UNIQUE (nombre);


--
-- TOC entry 4992 (class 2606 OID 17531)
-- Name: productos ukb2vi4382tjm9b8q2sgfiox2ec; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT ukb2vi4382tjm9b8q2sgfiox2ec UNIQUE (codigo_barras);


--
-- TOC entry 4968 (class 2606 OID 17525)
-- Name: comprobantes ukkrg0xm0s2cnbmc7rbyx91wm56; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT ukkrg0xm0s2cnbmc7rbyx91wm56 UNIQUE (tipo_comprobante, serie, correlativo);


--
-- TOC entry 4998 (class 2606 OID 17537)
-- Name: proveedores ukl2qkpg6gem3abown28yrhqjph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT ukl2qkpg6gem3abown28yrhqjph UNIQUE (ruc);


--
-- TOC entry 5002 (class 2606 OID 17539)
-- Name: usuarios ukm2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- TOC entry 4994 (class 2606 OID 17533)
-- Name: productos ukmlgw7js72hh2xtd4mvpdqfsbe; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT ukmlgw7js72hh2xtd4mvpdqfsbe UNIQUE (nombre);


--
-- TOC entry 5000 (class 2606 OID 17535)
-- Name: proveedores ukpobrqsjw818ifa8mgjoj04ek3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT ukpobrqsjw818ifa8mgjoj04ek3 UNIQUE (razon_social);


--
-- TOC entry 4958 (class 2606 OID 17521)
-- Name: categorias ukqcog8b7hps1hioi9onqwjdt6y; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT ukqcog8b7hps1hioi9onqwjdt6y UNIQUE (nombre);


--
-- TOC entry 4970 (class 2606 OID 17527)
-- Name: comprobantes ukt648b1d1o0tmip63ec61iqy9u; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT ukt648b1d1o0tmip63ec61iqy9u UNIQUE (venta_id);


--
-- TOC entry 5004 (class 2606 OID 17504)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 5006 (class 2606 OID 17519)
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id_venta);


--
-- TOC entry 5017 (class 2606 OID 17595)
-- Name: detalle_ventas fk2dn1sdhrbmva44wbs9fy6l7mn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT fk2dn1sdhrbmva44wbs9fy6l7mn FOREIGN KEY (venta_id) REFERENCES public.ventas(id_venta);


--
-- TOC entry 5026 (class 2606 OID 17635)
-- Name: productos fk2fwq10nwymfv7fumctxt9vpgb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk2fwq10nwymfv7fumctxt9vpgb FOREIGN KEY (categoria_id) REFERENCES public.categorias(id_categoria);


--
-- TOC entry 5020 (class 2606 OID 17610)
-- Name: movimientos fk2ofduyqqwmyyf07vue5g6iv7m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fk2ofduyqqwmyyf07vue5g6iv7m FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5028 (class 2606 OID 17650)
-- Name: ventas fk4dgjhccl2uuo8swmxlxb4ipb5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk4dgjhccl2uuo8swmxlxb4ipb5 FOREIGN KEY (cliente_id) REFERENCES public.clientes(id_cliente);


--
-- TOC entry 5008 (class 2606 OID 17550)
-- Name: compras fk4lnkw9964v2gf3b2sjbaealqw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT fk4lnkw9964v2gf3b2sjbaealqw FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5022 (class 2606 OID 17615)
-- Name: movimientos_caja fk8qr7tgyt87uemae5vdip26kbu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT fk8qr7tgyt87uemae5vdip26kbu FOREIGN KEY (caja_sesion_id) REFERENCES public.caja_sesiones(id_caja_sesion);


--
-- TOC entry 5010 (class 2606 OID 17555)
-- Name: comprobantes fk91bhhp01vm5iuarqgouaxyq3r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT fk91bhhp01vm5iuarqgouaxyq3r FOREIGN KEY (cliente_id) REFERENCES public.clientes(id_cliente);


--
-- TOC entry 5015 (class 2606 OID 17585)
-- Name: detalle_movimientos fk9f8wvbouthyryu9envcks4mm2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_movimientos
    ADD CONSTRAINT fk9f8wvbouthyryu9envcks4mm2 FOREIGN KEY (movimiento_id) REFERENCES public.movimientos(id_movimiento);


--
-- TOC entry 5009 (class 2606 OID 17545)
-- Name: compras fkabfd3b61ss0f7ebhao6evn5ec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compras
    ADD CONSTRAINT fkabfd3b61ss0f7ebhao6evn5ec FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id_proveedor);


--
-- TOC entry 5021 (class 2606 OID 17605)
-- Name: movimientos fkc06xjb8154x6gvojhusibla54; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT fkc06xjb8154x6gvojhusibla54 FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id_proveedor);


--
-- TOC entry 5029 (class 2606 OID 17655)
-- Name: ventas fkco9r9xjcdqtgd4nvnnolsr6ei; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkco9r9xjcdqtgd4nvnnolsr6ei FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5011 (class 2606 OID 17560)
-- Name: comprobantes fkev00246sx1ueaiwi3r7wc244q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT fkev00246sx1ueaiwi3r7wc244q FOREIGN KEY (venta_id) REFERENCES public.ventas(id_venta);


--
-- TOC entry 5012 (class 2606 OID 17570)
-- Name: detalle_compras fkjfq3nujil0c8aljhgb5gl3url; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_compras
    ADD CONSTRAINT fkjfq3nujil0c8aljhgb5gl3url FOREIGN KEY (lote_id) REFERENCES public.lotes(id_lote);


--
-- TOC entry 5027 (class 2606 OID 17640)
-- Name: productos fkjsfnjfkp0ioi3qh26dtarh4w9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fkjsfnjfkp0ioi3qh26dtarh4w9 FOREIGN KEY (laboratorio_id) REFERENCES public.laboratorios(id_laboratorio);


--
-- TOC entry 5016 (class 2606 OID 17580)
-- Name: detalle_movimientos fkkj5axmmlo0xuvcj1oa9vgu4u9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_movimientos
    ADD CONSTRAINT fkkj5axmmlo0xuvcj1oa9vgu4u9 FOREIGN KEY (lote_id) REFERENCES public.lotes(id_lote);


--
-- TOC entry 5018 (class 2606 OID 17590)
-- Name: detalle_ventas fkm5c10qg9d3ti9ktac659emrlq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT fkm5c10qg9d3ti9ktac659emrlq FOREIGN KEY (lote_id) REFERENCES public.lotes(id_lote);


--
-- TOC entry 5019 (class 2606 OID 17600)
-- Name: lotes fknnj5qqxdf1snlgaxjxtut4ow2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lotes
    ADD CONSTRAINT fknnj5qqxdf1snlgaxjxtut4ow2 FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto);


--
-- TOC entry 5024 (class 2606 OID 17625)
-- Name: pagos fknqvbcdwx4ry3lcqwayxda9hh8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fknqvbcdwx4ry3lcqwayxda9hh8 FOREIGN KEY (caja_sesion_id) REFERENCES public.caja_sesiones(id_caja_sesion);


--
-- TOC entry 5013 (class 2606 OID 17575)
-- Name: detalle_compras fkobinn960qd4nxk1b3b0n6aps1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_compras
    ADD CONSTRAINT fkobinn960qd4nxk1b3b0n6aps1 FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto);


--
-- TOC entry 5030 (class 2606 OID 17645)
-- Name: ventas fkqcikbotqln79py19m6ho28564; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fkqcikbotqln79py19m6ho28564 FOREIGN KEY (caja_sesion_id) REFERENCES public.caja_sesiones(id_caja_sesion);


--
-- TOC entry 5007 (class 2606 OID 17540)
-- Name: caja_sesiones fkqshlpyswvkyd6f0tm0rospdd6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_sesiones
    ADD CONSTRAINT fkqshlpyswvkyd6f0tm0rospdd6 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5025 (class 2606 OID 17630)
-- Name: pagos fkr2gojgwqy0othfw6qnrncedj3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fkr2gojgwqy0othfw6qnrncedj3 FOREIGN KEY (venta_id) REFERENCES public.ventas(id_venta);


--
-- TOC entry 5023 (class 2606 OID 17620)
-- Name: movimientos_caja fks5nbchxrylhj695yi5ucqfbsk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos_caja
    ADD CONSTRAINT fks5nbchxrylhj695yi5ucqfbsk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- TOC entry 5014 (class 2606 OID 17565)
-- Name: detalle_compras fks7ksdchwhuo5bv58t28iti0f0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_compras
    ADD CONSTRAINT fks7ksdchwhuo5bv58t28iti0f0 FOREIGN KEY (compra_id) REFERENCES public.compras(id_compra);


-- Completed on 2026-08-24 23:09:56

--
-- PostgreSQL database dump complete
--

\unrestrict 2uQwSnjd2dyN4DwmBFf1ddpnAeIFwWc4o5ZymFvnzTaV7NlrUQ3dHfyAsr51JkS

