-- Esquema base versionado. Los CREATE/ALTER son idempotentes para adoptar
-- instalaciones antiguas creadas previamente con Hibernate ddl-auto=update.

CREATE TABLE IF NOT EXISTS categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(1) DEFAULT 'A'
);

CREATE TABLE IF NOT EXISTS laboratorios (
    id_laboratorio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    estado VARCHAR(1) DEFAULT 'A',
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    creado_por VARCHAR(255),
    modificado_por VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(200) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    estado VARCHAR(1) DEFAULT 'A',
    fecha_creacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento VARCHAR(20) NOT NULL,
    numero_documento VARCHAR(15) NOT NULL UNIQUE,
    nombre_razon_social VARCHAR(200) NOT NULL,
    direccion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(200) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    correo VARCHAR(150),
    direccion VARCHAR(250),
    estado VARCHAR(1) DEFAULT 'A'
);

CREATE TABLE IF NOT EXISTS productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL UNIQUE,
    codigo_barras VARCHAR(50) UNIQUE,
    codigo_sunat VARCHAR(20),
    tipo_afectacion_igv VARCHAR(2) DEFAULT '10',
    principio_activo VARCHAR(200),
    presentacion VARCHAR(100),
    forma_farmaceutica VARCHAR(30),
    unidad_medida VARCHAR(20),
    precio_venta NUMERIC(10,2),
    stock_actual INTEGER DEFAULT 0,
    stock_minimo INTEGER DEFAULT 5,
    unidades_por_presentacion INTEGER DEFAULT 1,
    precio_presentacion NUMERIC(10,2),
    categoria_id INTEGER NOT NULL REFERENCES categorias(id_categoria),
    laboratorio_id INTEGER REFERENCES laboratorios(id_laboratorio),
    requiere_receta BOOLEAN DEFAULT FALSE,
    estado VARCHAR(1) DEFAULT 'A',
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    creado_por VARCHAR(255),
    modificado_por VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS lotes (
    id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_lote VARCHAR(50) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    stock_inicial INTEGER NOT NULL,
    stock_actual INTEGER NOT NULL,
    precio_compra NUMERIC(10,2),
    estado VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    producto_id INTEGER NOT NULL REFERENCES productos(id_producto)
);

CREATE TABLE IF NOT EXISTS caja_sesiones (
    id_caja_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    fecha_apertura TIMESTAMP NOT NULL,
    fecha_cierre TIMESTAMP,
    monto_inicial NUMERIC(10,2) NOT NULL,
    monto_final NUMERIC(10,2),
    estado VARCHAR(20) DEFAULT 'ABIERTA',
    fecha_creacion TIMESTAMP,
    fecha_modificacion TIMESTAMP,
    creado_por VARCHAR(255),
    modificado_por VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ventas (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_emision TIMESTAMP NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    cliente_id INTEGER REFERENCES clientes(id_cliente),
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    caja_sesion_id INTEGER NOT NULL REFERENCES caja_sesiones(id_caja_sesion),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    idempotency_key VARCHAR(64),
    referencia_receta VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS series_comprobante (
    id_serie INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    ultimo_correlativo BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_serie_comprobante_tipo_serie UNIQUE (tipo_comprobante, serie)
);

CREATE TABLE IF NOT EXISTS comprobantes (
    id_comprobante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL UNIQUE REFERENCES ventas(id_venta),
    tipo_comprobante VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    correlativo VARCHAR(20) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    cliente_id INTEGER REFERENCES clientes(id_cliente),
    subtotal NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    CONSTRAINT uk_comprobante_tipo_serie_correlativo
        UNIQUE (tipo_comprobante, serie, correlativo)
);

CREATE TABLE IF NOT EXISTS pagos (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL REFERENCES ventas(id_venta),
    metodo_pago VARCHAR(20) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    monto_recibido NUMERIC(10,2) NOT NULL,
    vuelto NUMERIC(10,2) NOT NULL DEFAULT 0,
    fecha_pago TIMESTAMP NOT NULL,
    referencia VARCHAR(100),
    caja_sesion_id INTEGER NOT NULL REFERENCES caja_sesiones(id_caja_sesion),
    estado VARCHAR(20) NOT NULL DEFAULT 'APROBADO'
);

CREATE TABLE IF NOT EXISTS movimientos_caja (
    id_movimiento_caja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_sesion_id INTEGER NOT NULL REFERENCES caja_sesiones(id_caja_sesion),
    tipo_movimiento VARCHAR(20) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS compras (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    documento VARCHAR(50) NOT NULL,
    fecha_compra TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    total NUMERIC(10,2) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA',
    idempotency_key VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS detalle_compras (
    id_detalle_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL REFERENCES compras(id_compra),
    producto_id INTEGER NOT NULL REFERENCES productos(id_producto),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    costo_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS detalle_ventas (
    id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL REFERENCES ventas(id_venta),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,4) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    base_imponible NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    tipo_afectacion_igv VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS movimientos (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_movimiento TIMESTAMP NOT NULL,
    tipo_movimiento VARCHAR(30) NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    proveedor_id INTEGER REFERENCES proveedores(id_proveedor),
    motivo VARCHAR(300),
    referencia_anulacion INTEGER,
    referencia_tipo VARCHAR(30),
    referencia_id INTEGER,
    idempotency_key VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS detalle_movimientos (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id INTEGER NOT NULL REFERENCES movimientos(id_movimiento),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    stock_lote_anterior INTEGER NOT NULL,
    stock_lote_posterior INTEGER NOT NULL,
    stock_producto_anterior INTEGER NOT NULL,
    stock_producto_posterior INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS inventario_conteos (
    id_conteo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_finalizacion TIMESTAMP NOT NULL,
    motivo VARCHAR(300) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario)
);

CREATE TABLE IF NOT EXISTS inventario_conteo_detalles (
    id_detalle_conteo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conteo_id INTEGER NOT NULL REFERENCES inventario_conteos(id_conteo),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    stock_sistema INTEGER NOT NULL,
    stock_contado INTEGER NOT NULL,
    diferencia INTEGER NOT NULL,
    CONSTRAINT uk_conteo_lote UNIQUE (conteo_id, lote_id)
);

-- Adopción de bases creadas antes de Flyway.
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS referencia_receta VARCHAR(100);
ALTER TABLE compras ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);
ALTER TABLE movimientos ADD COLUMN IF NOT EXISTS referencia_tipo VARCHAR(30);
ALTER TABLE movimientos ADD COLUMN IF NOT EXISTS referencia_id INTEGER;
ALTER TABLE movimientos ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS monto_recibido NUMERIC(10,2);
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS vuelto NUMERIC(10,2);
ALTER TABLE detalle_ventas ADD COLUMN IF NOT EXISTS base_imponible NUMERIC(10,2);
ALTER TABLE detalle_ventas ADD COLUMN IF NOT EXISTS igv NUMERIC(10,2);
ALTER TABLE detalle_ventas ADD COLUMN IF NOT EXISTS tipo_afectacion_igv VARCHAR(2);
ALTER TABLE detalle_movimientos ADD COLUMN IF NOT EXISTS stock_lote_anterior INTEGER;
ALTER TABLE detalle_movimientos ADD COLUMN IF NOT EXISTS stock_lote_posterior INTEGER;
ALTER TABLE detalle_movimientos ADD COLUMN IF NOT EXISTS stock_producto_anterior INTEGER;
ALTER TABLE detalle_movimientos ADD COLUMN IF NOT EXISTS stock_producto_posterior INTEGER;
ALTER TABLE detalle_ventas ALTER COLUMN precio_unitario TYPE NUMERIC(12,4);

UPDATE pagos SET monto_recibido = monto WHERE monto_recibido IS NULL;
UPDATE pagos SET vuelto = 0 WHERE vuelto IS NULL;
UPDATE detalle_ventas
SET base_imponible = ROUND(subtotal / 1.18, 2)
WHERE base_imponible IS NULL;
UPDATE detalle_ventas
SET igv = subtotal - base_imponible
WHERE igv IS NULL;
UPDATE detalle_ventas
SET tipo_afectacion_igv = '10'
WHERE tipo_afectacion_igv IS NULL;
UPDATE detalle_movimientos SET stock_lote_anterior = 0 WHERE stock_lote_anterior IS NULL;
UPDATE detalle_movimientos SET stock_lote_posterior = 0 WHERE stock_lote_posterior IS NULL;
UPDATE detalle_movimientos SET stock_producto_anterior = 0 WHERE stock_producto_anterior IS NULL;
UPDATE detalle_movimientos SET stock_producto_posterior = 0 WHERE stock_producto_posterior IS NULL;

ALTER TABLE pagos ALTER COLUMN monto_recibido SET NOT NULL;
ALTER TABLE pagos ALTER COLUMN vuelto SET NOT NULL;
ALTER TABLE detalle_ventas ALTER COLUMN base_imponible SET NOT NULL;
ALTER TABLE detalle_ventas ALTER COLUMN igv SET NOT NULL;
ALTER TABLE detalle_ventas ALTER COLUMN tipo_afectacion_igv SET NOT NULL;
ALTER TABLE detalle_movimientos ALTER COLUMN stock_lote_anterior SET NOT NULL;
ALTER TABLE detalle_movimientos ALTER COLUMN stock_lote_posterior SET NOT NULL;
ALTER TABLE detalle_movimientos ALTER COLUMN stock_producto_anterior SET NOT NULL;
ALTER TABLE detalle_movimientos ALTER COLUMN stock_producto_posterior SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_ventas_idempotency
    ON ventas(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_compras_idempotency
    ON compras(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_movimientos_idempotency
    ON movimientos(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_compras_proveedor_documento
    ON compras(proveedor_id, UPPER(documento));
CREATE UNIQUE INDEX IF NOT EXISTS uk_lotes_producto_codigo
    ON lotes(producto_id, UPPER(codigo_lote));

CREATE INDEX IF NOT EXISTS ix_lotes_producto_estado_vencimiento
    ON lotes(producto_id, estado, fecha_vencimiento);
CREATE INDEX IF NOT EXISTS ix_ventas_fecha ON ventas(fecha_emision);
CREATE INDEX IF NOT EXISTS ix_ventas_cliente ON ventas(cliente_id);
CREATE INDEX IF NOT EXISTS ix_ventas_caja ON ventas(caja_sesion_id);
CREATE INDEX IF NOT EXISTS ix_comprobantes_serie_correlativo
    ON comprobantes(serie, correlativo);
CREATE INDEX IF NOT EXISTS ix_movimientos_fecha ON movimientos(fecha_movimiento);
CREATE INDEX IF NOT EXISTS ix_detalle_movimientos_lote ON detalle_movimientos(lote_id);
CREATE INDEX IF NOT EXISTS ix_compras_fecha ON compras(fecha_compra);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_producto_stock_no_negativo') THEN
        ALTER TABLE productos ADD CONSTRAINT ck_producto_stock_no_negativo CHECK (stock_actual >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_lote_stock_no_negativo') THEN
        ALTER TABLE lotes ADD CONSTRAINT ck_lote_stock_no_negativo
            CHECK (stock_inicial >= 0 AND stock_actual >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_detalle_compra_cantidad_positiva') THEN
        ALTER TABLE detalle_compras ADD CONSTRAINT ck_detalle_compra_cantidad_positiva
            CHECK (cantidad > 0 AND costo_unitario >= 0 AND subtotal >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_detalle_venta_cantidad_positiva') THEN
        ALTER TABLE detalle_ventas ADD CONSTRAINT ck_detalle_venta_cantidad_positiva
            CHECK (cantidad > 0 AND precio_unitario >= 0 AND subtotal >= 0 AND base_imponible >= 0 AND igv >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_pago_montos_validos') THEN
        ALTER TABLE pagos ADD CONSTRAINT ck_pago_montos_validos
            CHECK (monto > 0 AND monto_recibido >= monto AND vuelto >= 0
                   AND monto_recibido = monto + vuelto);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_venta_montos_validos') THEN
        ALTER TABLE ventas ADD CONSTRAINT ck_venta_montos_validos
            CHECK (subtotal >= 0 AND igv >= 0 AND total >= 0 AND total = subtotal + igv);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_conteo_stock_no_negativo') THEN
        ALTER TABLE inventario_conteo_detalles ADD CONSTRAINT ck_conteo_stock_no_negativo
            CHECK (stock_sistema >= 0 AND stock_contado >= 0 AND diferencia = stock_contado - stock_sistema);
    END IF;
END $$;

INSERT INTO series_comprobante(tipo_comprobante, serie, ultimo_correlativo)
VALUES
    ('BOLETA', 'B001', COALESCE((SELECT MAX(CAST(correlativo AS BIGINT)) FROM comprobantes WHERE tipo_comprobante = 'BOLETA' AND correlativo ~ '^[0-9]+$'), 0)),
    ('FACTURA', 'F001', COALESCE((SELECT MAX(CAST(correlativo AS BIGINT)) FROM comprobantes WHERE tipo_comprobante = 'FACTURA' AND correlativo ~ '^[0-9]+$'), 0)),
    ('TICKET', 'T001', COALESCE((SELECT MAX(CAST(correlativo AS BIGINT)) FROM comprobantes WHERE tipo_comprobante = 'TICKET' AND correlativo ~ '^[0-9]+$'), 0))
ON CONFLICT (tipo_comprobante, serie) DO NOTHING;
