-- Segunda fase: devoluciones, arqueo, recetas, recepción de compras,
-- documentos electrónicos SUNAT y reportes de precios DIGEMID.

ALTER TABLE productos ADD COLUMN IF NOT EXISTS condicion_venta VARCHAR(30);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS registro_sanitario VARCHAR(50);
UPDATE productos
SET condicion_venta = CASE WHEN COALESCE(requiere_receta, FALSE)
                           THEN 'CON_RECETA_MEDICA' ELSE 'SIN_RECETA_MEDICA' END
WHERE condicion_venta IS NULL;
ALTER TABLE productos ALTER COLUMN condicion_venta SET NOT NULL;

CREATE TABLE IF NOT EXISTS recetas (
    id_receta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(60) NOT NULL UNIQUE,
    cliente_id INTEGER REFERENCES clientes(id_cliente),
    paciente_nombre VARCHAR(200) NOT NULL,
    paciente_documento VARCHAR(20),
    medico_nombre VARCHAR(200) NOT NULL,
    medico_colegiatura VARCHAR(30) NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE,
    condicion_venta VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    retenida_en TIMESTAMP,
    observaciones VARCHAR(500),
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    fecha_registro TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS receta_detalles (
    id_receta_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_id INTEGER NOT NULL REFERENCES recetas(id_receta),
    producto_id INTEGER NOT NULL REFERENCES productos(id_producto),
    cantidad_autorizada INTEGER NOT NULL,
    cantidad_dispensada INTEGER NOT NULL DEFAULT 0,
    indicaciones VARCHAR(300),
    CONSTRAINT uk_receta_producto UNIQUE (receta_id, producto_id),
    CONSTRAINT ck_receta_cantidades CHECK (
        cantidad_autorizada > 0 AND cantidad_dispensada >= 0
        AND cantidad_dispensada <= cantidad_autorizada
    )
);

ALTER TABLE ventas ADD COLUMN IF NOT EXISTS receta_id INTEGER REFERENCES recetas(id_receta);

ALTER TABLE caja_sesiones ADD COLUMN IF NOT EXISTS monto_esperado NUMERIC(10,2);
ALTER TABLE caja_sesiones ADD COLUMN IF NOT EXISTS diferencia NUMERIC(10,2);
ALTER TABLE caja_sesiones ADD COLUMN IF NOT EXISTS observaciones_cierre VARCHAR(500);
ALTER TABLE caja_sesiones ADD COLUMN IF NOT EXISTS requiere_revision BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE movimientos_caja ADD COLUMN IF NOT EXISTS referencia_tipo VARCHAR(30);
ALTER TABLE movimientos_caja ADD COLUMN IF NOT EXISTS referencia_id INTEGER;
ALTER TABLE movimientos_caja ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS uk_movimiento_caja_idempotency
    ON movimientos_caja(idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS arqueos_caja (
    id_arqueo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_sesion_id INTEGER NOT NULL UNIQUE REFERENCES caja_sesiones(id_caja_sesion),
    total_contado NUMERIC(10,2) NOT NULL,
    saldo_esperado NUMERIC(10,2) NOT NULL,
    diferencia NUMERIC(10,2) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    observaciones VARCHAR(500),
    fecha TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    aprobado_por_id INTEGER REFERENCES usuarios(id_usuario),
    fecha_aprobacion TIMESTAMP,
    observacion_aprobacion VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS arqueo_denominaciones (
    id_arqueo_denominacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arqueo_id INTEGER NOT NULL REFERENCES arqueos_caja(id_arqueo),
    denominacion NUMERIC(10,2) NOT NULL,
    cantidad INTEGER NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    CONSTRAINT uk_arqueo_denominacion UNIQUE (arqueo_id, denominacion),
    CONSTRAINT ck_arqueo_denominacion CHECK (
        denominacion > 0 AND cantidad >= 0 AND subtotal = denominacion * cantidad
    )
);

CREATE TABLE IF NOT EXISTS devoluciones_venta (
    id_devolucion_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id INTEGER NOT NULL REFERENCES ventas(id_venta),
    caja_sesion_id INTEGER NOT NULL REFERENCES caja_sesiones(id_caja_sesion),
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    fecha TIMESTAMP NOT NULL,
    motivo VARCHAR(300) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    metodo_reembolso VARCHAR(20),
    referencia_reembolso VARCHAR(100),
    subtotal NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL UNIQUE,
    CONSTRAINT ck_devolucion_venta_montos CHECK (
        subtotal >= 0 AND igv >= 0 AND total > 0 AND total = subtotal + igv
    )
);

CREATE TABLE IF NOT EXISTS devolucion_venta_detalles (
    id_devolucion_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_venta_id INTEGER NOT NULL REFERENCES devoluciones_venta(id_devolucion_venta),
    detalle_venta_id INTEGER NOT NULL REFERENCES detalle_ventas(id_detalle_venta),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    base_imponible NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_devolucion_venta_detalle CHECK (
        cantidad > 0 AND subtotal >= 0 AND base_imponible >= 0 AND igv >= 0
    )
);

CREATE TABLE IF NOT EXISTS reembolsos_venta (
    id_reembolso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_venta_id INTEGER NOT NULL REFERENCES devoluciones_venta(id_devolucion_venta),
    metodo_pago VARCHAR(20) NOT NULL,
    monto NUMERIC(10,2) NOT NULL,
    referencia VARCHAR(100),
    CONSTRAINT ck_reembolso_venta_monto CHECK (monto > 0)
);

ALTER TABLE compras ADD COLUMN IF NOT EXISTS fecha_esperada DATE;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS observaciones VARCHAR(500);
ALTER TABLE detalle_compras ADD COLUMN IF NOT EXISTS cantidad_recibida INTEGER NOT NULL DEFAULT 0;
ALTER TABLE detalle_compras ALTER COLUMN lote_id DROP NOT NULL;
UPDATE detalle_compras SET cantidad_recibida = cantidad WHERE cantidad_recibida = 0;
UPDATE compras SET estado = 'RECIBIDA' WHERE estado = 'REGISTRADA';

CREATE TABLE IF NOT EXISTS recepciones_compra (
    id_recepcion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL REFERENCES compras(id_compra),
    documento_proveedor VARCHAR(60),
    fecha TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    estado VARCHAR(20) NOT NULL,
    observaciones VARCHAR(500),
    idempotency_key VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS recepcion_compra_detalles (
    id_recepcion_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recepcion_id INTEGER NOT NULL REFERENCES recepciones_compra(id_recepcion),
    detalle_compra_id INTEGER NOT NULL REFERENCES detalle_compras(id_detalle_compra),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    costo_unitario NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_recepcion_compra_detalle CHECK (cantidad > 0 AND costo_unitario >= 0)
);

-- Las compras creadas antes de V3 ya afectaron stock. Se materializa una
-- recepción histórica para conservar su trazabilidad y permitir devoluciones.
INSERT INTO recepciones_compra (
    compra_id, documento_proveedor, fecha, usuario_id, estado, observaciones, idempotency_key
)
SELECT c.id_compra, c.documento, c.fecha_compra, c.usuario_id, 'CONFIRMADA',
       'Recepción histórica creada por migración V3', 'MIGRACION-V3-COMPRA-' || c.id_compra
FROM compras c
WHERE EXISTS (
    SELECT 1 FROM detalle_compras dc
    WHERE dc.compra_id = c.id_compra AND dc.lote_id IS NOT NULL
)
AND NOT EXISTS (
    SELECT 1 FROM recepciones_compra rc WHERE rc.compra_id = c.id_compra
);

INSERT INTO recepcion_compra_detalles (
    recepcion_id, detalle_compra_id, lote_id, cantidad, costo_unitario
)
SELECT rc.id_recepcion, dc.id_detalle_compra, dc.lote_id, dc.cantidad, dc.costo_unitario
FROM detalle_compras dc
JOIN recepciones_compra rc
  ON rc.compra_id = dc.compra_id
 AND rc.idempotency_key = 'MIGRACION-V3-COMPRA-' || dc.compra_id
WHERE dc.lote_id IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM recepcion_compra_detalles rcd
    WHERE rcd.recepcion_id = rc.id_recepcion
      AND rcd.detalle_compra_id = dc.id_detalle_compra
      AND rcd.lote_id = dc.lote_id
);

CREATE TABLE IF NOT EXISTS devoluciones_proveedor (
    id_devolucion_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL REFERENCES compras(id_compra),
    proveedor_id INTEGER NOT NULL REFERENCES proveedores(id_proveedor),
    fecha TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    motivo VARCHAR(300) NOT NULL,
    documento_referencia VARCHAR(60),
    estado VARCHAR(20) NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS devolucion_proveedor_detalles (
    id_devolucion_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_proveedor_id INTEGER NOT NULL REFERENCES devoluciones_proveedor(id_devolucion_proveedor),
    detalle_compra_id INTEGER NOT NULL REFERENCES detalle_compras(id_detalle_compra),
    lote_id INTEGER NOT NULL REFERENCES lotes(id_lote),
    cantidad INTEGER NOT NULL,
    costo_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    CONSTRAINT ck_devolucion_proveedor_detalle CHECK (
        cantidad > 0 AND costo_unitario >= 0 AND subtotal >= 0
    )
);

CREATE TABLE IF NOT EXISTS series_documento_electronico (
    id_serie INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    ultimo_correlativo BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_serie_documento_electronico UNIQUE (tipo_documento, serie)
);

CREATE TABLE IF NOT EXISTS documentos_electronicos (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comprobante_id INTEGER REFERENCES comprobantes(id_comprobante),
    devolucion_venta_id INTEGER REFERENCES devoluciones_venta(id_devolucion_venta),
    tipo_documento VARCHAR(20) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    correlativo VARCHAR(20) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL,
    xml TEXT,
    hash_xml VARCHAR(64),
    cdr BYTEA,
    codigo_respuesta VARCHAR(20),
    descripcion_respuesta VARCHAR(1000),
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_intento TIMESTAMP,
    siguiente_intento TIMESTAMP,
    CONSTRAINT uk_documento_electronico_numero UNIQUE (tipo_documento, serie, correlativo)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_documento_electronico_comprobante
    ON documentos_electronicos(comprobante_id) WHERE comprobante_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_documento_electronico_devolucion
    ON documentos_electronicos(devolucion_venta_id) WHERE devolucion_venta_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS resumenes_diarios_sunat (
    id_resumen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificador VARCHAR(25) UNIQUE,
    fecha_referencia DATE NOT NULL,
    fecha_generacion TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL,
    xml TEXT,
    hash_xml VARCHAR(64),
    ticket VARCHAR(100),
    cdr BYTEA,
    codigo_respuesta VARCHAR(20),
    descripcion_respuesta VARCHAR(1000),
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_intento TIMESTAMP,
    siguiente_intento TIMESTAMP
);

ALTER TABLE documentos_electronicos
    ADD COLUMN IF NOT EXISTS resumen_diario_id INTEGER REFERENCES resumenes_diarios_sunat(id_resumen);

CREATE INDEX IF NOT EXISTS ix_documentos_electronicos_resumen
    ON documentos_electronicos(resumen_diario_id);
CREATE INDEX IF NOT EXISTS ix_resumenes_diarios_estado
    ON resumenes_diarios_sunat(estado, siguiente_intento);

CREATE TABLE IF NOT EXISTS reportes_precios_digemid (
    id_reporte INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo VARCHAR(7) NOT NULL UNIQUE,
    fecha_generacion TIMESTAMP NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id_usuario),
    estado VARCHAR(20) NOT NULL,
    cantidad_productos INTEGER NOT NULL,
    hash_archivo VARCHAR(64) NOT NULL,
    archivo_csv TEXT NOT NULL,
    fecha_envio TIMESTAMP,
    constancia VARCHAR(100),
    observaciones VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS reporte_precios_digemid_detalles (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporte_id INTEGER NOT NULL REFERENCES reportes_precios_digemid(id_reporte),
    producto_id INTEGER NOT NULL REFERENCES productos(id_producto),
    registro_sanitario VARCHAR(50) NOT NULL,
    nombre_producto VARCHAR(200) NOT NULL,
    presentacion VARCHAR(100),
    precio_venta_publico NUMERIC(10,2) NOT NULL,
    stock_disponible INTEGER NOT NULL,
    fecha_vigencia DATE NOT NULL,
    CONSTRAINT uk_reporte_digemid_producto UNIQUE (reporte_id, producto_id)
);

CREATE INDEX IF NOT EXISTS ix_devoluciones_venta_venta ON devoluciones_venta(venta_id);
CREATE INDEX IF NOT EXISTS ix_recepciones_compra_compra ON recepciones_compra(compra_id);
CREATE INDEX IF NOT EXISTS ix_devoluciones_proveedor_compra ON devoluciones_proveedor(compra_id);
CREATE INDEX IF NOT EXISTS ix_documentos_electronicos_estado ON documentos_electronicos(estado, siguiente_intento);
CREATE INDEX IF NOT EXISTS ix_recetas_estado_vencimiento ON recetas(estado, fecha_vencimiento);

INSERT INTO series_documento_electronico(tipo_documento, serie, ultimo_correlativo)
VALUES ('NOTA_CREDITO', 'FC01', 0), ('NOTA_CREDITO', 'BC01', 0)
ON CONFLICT (tipo_documento, serie) DO NOTHING;
